const bookDate =[{
    name: "The Hare With Amber Eyes",
    image: "image/book1.png",
    price: "$50",
    stock: 50,
},
{
    name: "The war of  Art",
    image: "image/book2.png",
    price: "$60",
    stock: 0,
},
{
    name: "The Hare With Amber Eyes",
    image: "image/book3.png",
    price: "$25",
    stock: 0,
},
{
    name: "The Immortals of Meluha",
    image: "image/book4.png",
    price: "$80",
    stock: 10,
},
{
    name: "Life Is What You  Make It",
    image: "image/book6.png",
    price: "$200",
    stock: 0,
},
{
    name: "The Hare With Amber Eyes",
    image: "image/book7.png",
    price: "$200",
    stock: 0,
},
{
    name: "The war of  Art",
    image: "image/book8.png",
    price: "$150",
    stock: 0,
},
{
    name: "The Hare With Amber Eyes",
    image: "image/book9.png",
    price: "$100",
    stock: 0,
},
{
    name: "The Immortals of Meluha",
    image: "image/book10.png",
    price: "$152",
    stock: 30,
},
{
    name: "Life Is What You  Make It",
    image: "image/book11.png",
    price: "$200",
    stock: 30,
},
{
    name: "The Hare With Amber Eyes",
    image: "image/book12.png",
    price: "$220",
    stock: 0,
},
{
    name: "The war of  Art",
    image: "image/book13.png",
    price: "$10",
    stock: 0,
},
{
    name: "The Hare With Amber Eyes",
    image: "image/book14.png",
    price: "$22",
    stock: 20,
},
{
    name: "The Immortals of Meluha",
    image: "image/book8.png",
    price: "$300",
    stock: 0,
},
{
    name: "Life Is What You  Make It",
    image: "image/book15.png",
    price: "$205",
    stock: 10,
},
{
    name: "The Hare With Amber Eyes",
    image: "image/book12.png",
    price: "$220",
    stock: 0,
},
{
    name: "The war of  Art",
    image: "image/book13.png",
    price: "$10",
    stock: 0,
},
{
    name: "The Hare With Amber Eyes",
    image: "image/book14.png",
    price: "$22",
    stock: 0,
},
{
    name: "The Immortals of Meluha",
    image: "image/book8.png",
    price: "$300",
    stock: 0,
},
{
    name: "Life Is What You  Make It",
    image: "image/book15.png",
    price: "$205",
    stock: 30,
},
]

export default bookDate